---
title: "Untitled"
author: "Chloe Chung"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(here)
source(here("source", "get_lib.R"))
```

#Gapminder
```{r}
gap <- fread (here("data", "gapminder.csv"))
head(gap)

length(gap$year)
length(unique(gap$year))

my_ten = unique(gap$country) [1:10]

```

## Selecting Rows and Columns 
```{r}
head(gap)

#select columns 
gap %>% select(c("pop", "year")) %>% head()

#parameter is something you pass on to a funciton. here, 'select' is the function. 

#select from the dataset 

gap %>% select (year, pop, lifeExp)

# assign these variables to a new dataset
gap_subset <- select(gap, year, pop, lifeExp)
dim(gap_subset)
head(gap_subset)

#filter rows

gap %>% filter (country == "Afghanistan") %>% head()

gap %>% filter (country %in% my_ten) %>% head()

gap %>% select (c("pop", "year")) %>% 
        select (c("pop", "year")) %>% 
        head() 
```


##Plot 

```{r echo=FALSE}
gap %>% ggplot (aes(x=year, y=pop)) + geom_point()

```

### My Ten 

```{r fig.height=11}
gap %>% filter (country %in% my_ten) %>% 
        ggplot(aes(x=year, y=pop, color=country)) + geom_point() + theme(legend.position = "top")
```

### Sub Plots 
```{r}
# return all rows in Asia with a GDP per capita above or equal to 30K
p1 <- gap %>% filter (continent == "Asia" & gdpPercap >= 30000) %>% 
        ggplot (aes(x=year, y=pop, color=country)) + geom_point() + theme(legend.position = "top")
p2 <- gap %>% filter (continent == "Asia" & gdpPercap >= 30000) %>% 
        filter(pop<5000000) %>% 
  ggplot (aes(x=year, y=pop, color=country)) + geom_point() + theme(legend.position = "top")
p1
p2

p1|p2



```

## Summary 
```{r}

# look at the continents we have (the number of rows that says these continents)
table(gap$continent)

#dim is dimensions
dim(gap)

head(gap)

gap %>% filter(year== 1952) %>% 
    group_by(country) %>% reframe(ave = sum(gdpPercap)) %>% 
        ggplot (aes(x=country, y=ave)) + 
  geom_col()



```

## solution 

```{r}
head(gap)


gap %>% filter(year %in% c(1952, 1962, 1982)) %>% 
    filter(country %in% unique (gap$country) [1:20]) %>% 
    ggplot(aes(x=year, y=pop, color=country)) +
    geom_point() +theme(legend.position = "top")



